package com.xuanhan.vuedemo.DAO;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xuanhan.vuedemo.entity.User;
import org.apache.ibatis.annotations.Mapper;


public interface UserMapper extends BaseMapper<User> {

    User selectOne(User user);
    User selectByUsername(User user);
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table user
//     *
//     * @mbg.generated Sun Jan 09 20:55:28 CST 2022
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table user
//     *
//     * @mbg.generated Sun Jan 09 20:55:28 CST 2022
//     */
//    int insert(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table user
//     *
//     * @mbg.generated Sun Jan 09 20:55:28 CST 2022
//     */
//    int insertSelective(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table user
//     *
//     * @mbg.generated Sun Jan 09 20:55:28 CST 2022
//     */
//    User selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table user
//     *
//     * @mbg.generated Sun Jan 09 20:55:28 CST 2022
//     */
//    int updateByPrimaryKeySelective(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table user
//     *
//     * @mbg.generated Sun Jan 09 20:55:28 CST 2022
//     */
//    int updateByPrimaryKey(User record);
}